### ISSUE TITLE
Add an `attributes` field to all statements

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/trunk#10]
I want to introduce a new `Attributes` structure and relevant field to all statements so that we can store things like `start_line`, `end_line` and any comments on the statement.

**Comment by edsrzf** [comment]
It might be better to use a different name than "attributes", since that name also refers to a [PHP language feature](https://www.php.net/manual/en/language.attributes.overview.php). The nikic/php-parser usage of "attributes" likely predates PHP attributes. "Properties" would be similarly confusing.

Other ideas: (I don't love any of these)
* Context
* Data
* Detail
* Extra

**Comment by ryangjchandler** [comment]
Yeah, I'm open to naming suggestions.
